package main

import (
	"context"
	"fmt"
	"log/slog"
	"maps"
	"net"
	"os"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	backoff "github.com/cenkalti/backoff/v4"
	"github.com/osism/ovn-network-agent/internal/nbdb"
	"github.com/osism/ovn-network-agent/internal/sbdb"
	"github.com/ovn-kubernetes/libovsdb/cache"
	"github.com/ovn-kubernetes/libovsdb/client"
	"github.com/ovn-kubernetes/libovsdb/model"
	"github.com/ovn-kubernetes/libovsdb/ovsdb"
)

const eventDebounceInterval = 500 * time.Millisecond

// reconcileDebounceInterval coalesces multiple state refreshes (SB + NB)
// into a single reconciliation trigger.
const reconcileDebounceInterval = 100 * time.Millisecond

// =============================================================================
// OVN database models
// =============================================================================
//
// The models are generated by libovsdb's modelgen from the OVN schemas checked
// in under schemas/ (see docs/contributing/ovsdb-models.md). They are aliased —
// not wrapped — so the whole agent keeps using the short SB*/NB* names while the
// column definitions themselves are regenerated rather than hand-maintained:
// picking up a new OVN column is `make models-gen`, not a hand-edited struct
// that silently disagrees with the server.
//
// Only the eight tables below are registered in the client database models, so
// connect-time schema validation stays scoped to what the agent actually reads
// and writes. The monitors additionally project explicit column lists — see
// Connect — because a generated model carries every column of its table, and
// monitoring a hot one (Chassis.nb_cfg changes on every northd round) would
// storm the debounce loop.

type (
	// OVN Southbound
	SBPortBinding = sbdb.PortBinding
	SBChassis     = sbdb.Chassis

	// OVN Northbound
	NBNAT                      = nbdb.NAT
	NBLogicalRouter            = nbdb.LogicalRouter
	NBLogicalRouterPort        = nbdb.LogicalRouterPort
	NBLogicalRouterStaticRoute = nbdb.LogicalRouterStaticRoute
	NBStaticMACBinding         = nbdb.StaticMACBinding
	NBGatewayChassis           = nbdb.GatewayChassis
)

// =============================================================================
// OVN Client wrapper
// =============================================================================

// ovsdbClient is the interface for OVSDB clients.
// The SB client is read-only; the NB client also performs writes
// (static routes, MAC bindings).
type ovsdbClient interface {
	Connect(context.Context) error
	Close()
	Connected() bool
	Cache() *cache.TableCache
	NewMonitor(...client.MonitorOption) *client.Monitor
	Monitor(context.Context, *client.Monitor) (client.MonitorCookie, error)
	List(ctx context.Context, result interface{}) error
	Create(models ...model.Model) ([]ovsdb.Operation, error)
	Where(models ...model.Model) client.ConditionalAPI
	Transact(ctx context.Context, ops ...ovsdb.Operation) ([]ovsdb.OperationResult, error)
}

// LocalnetSegment describes the localnet segment (provider network) that a
// locally-active router's external network is attached to. A nil VLANTag
// means a flat (untagged) network.
type LocalnetSegment struct {
	LocalnetPort string // SB localnet Port_Binding logical_port name
	NetworkName  string // options:network_name of the localnet port (the physnet)
	VLANTag      *int   // SB Port_Binding tag; nil = flat
}

// LocalRouterInfo describes a logical router whose gateway is active on this chassis.
type LocalRouterInfo struct {
	RouterName  string           // NB Logical_Router name
	RouterUUID  string           // NB Logical_Router UUID
	LRPName     string           // NB Logical_Router_Port name (e.g. "lrp-abc123")
	LRPUUID     string           // NB Logical_Router_Port UUID
	LRPMAC      string           // NB Logical_Router_Port MAC (e.g. "fa:16:3e:xx:xx:xx")
	LRPNetworks []string         // NB Logical_Router_Port networks (e.g. ["198.51.100.11/24"])
	CRPort      string           // SB chassisredirect logical_port (e.g. "cr-lrp-abc123")
	Segment     *LocalnetSegment // localnet segment of the external network; nil = unresolved
	// GatewayChassisUUIDs are the LRP's Gateway_Chassis row UUIDs, carried
	// straight from the NB reference column so EnsureActivePriorityLead can
	// group HA rows by LRP without parsing their names.
	GatewayChassisUUIDs []string
}

// segmentName returns the localnet port name of a router's segment, or ""
// (the fallback segment) when the segment is unresolved.
func segmentName(seg *LocalnetSegment) string {
	if seg == nil {
		return ""
	}
	return seg.LocalnetPort
}

// OVNState is a plain, lock-free snapshot of the agent's derived OVN view. It
// carries no mutex: ovnStateHolder guards the live copy and GetState hands out
// a deep clone, so a snapshot can be read without synchronisation and never
// aliases the holder's state. Splitting the guard from the value removes the
// hand-maintained-copy hazard where a field added to the struct but forgotten
// in the copy silently yielded a zero-value snapshot.
type OVNState struct {
	// Derived state
	LocalChassisName string

	// Multi-router gateway state: routers whose chassisredirect port
	// is active on this chassis.
	LocalRouters    []LocalRouterInfo
	HasLocalRouters bool

	// SNAT external IPs from NB, filtered to only locally-active routers.
	SNATIPs []string // snat external IPs

	// NATIPToRouterMAC maps each FIP/SNAT external IP to the MAC of the
	// router port that owns it. Used by hairpin flows to set dl_dst so
	// that OVN's L2 lookup delivers the reflected packet to the correct
	// router port.
	NATIPToRouterMAC map[string]string

	// NATIPToSegment maps each FIP/SNAT external IP to the localnet port
	// name of the segment its external network is on. IPs whose segment
	// is unresolved are absent from the map (the "" fallback segment).
	NATIPToSegment map[string]string

	// Networks auto-discovered from Logical_Router_Port.Networks of locally-active routers.
	DiscoveredNetworks []*net.IPNet

	// AllChassisNames is the set of chassis hostnames currently present in
	// the SB Chassis table. Used for stale chassis cleanup.
	AllChassisNames map[string]bool

	// Gen is the refreshState pass that published this state. It orders a
	// snapshot against a pending failover observation, so that a reconcile
	// only consumes an observation its own snapshot already reflects — see
	// takeFailoverObservedAt.
	Gen uint64
}

// clone returns a deep copy of s in which every reference-typed field is
// re-allocated, so a snapshot handed to a caller shares no backing array or map
// with — and cannot be mutated through — the holder's live state. Growing
// OVNState with a new slice/map/pointer field is a one-line edit here; the
// clone-completeness test fails until it is made.
func (s OVNState) clone() OVNState {
	out := s // scalar fields (LocalChassisName, HasLocalRouters) copy directly
	out.LocalRouters = append([]LocalRouterInfo{}, s.LocalRouters...)
	out.SNATIPs = append([]string{}, s.SNATIPs...)
	out.DiscoveredNetworks = append([]*net.IPNet{}, s.DiscoveredNetworks...)
	out.NATIPToRouterMAC = cloneMap(s.NATIPToRouterMAC)
	out.NATIPToSegment = cloneMap(s.NATIPToSegment)
	out.AllChassisNames = cloneMap(s.AllChassisNames)
	return out
}

// cloneMap returns a non-nil copy of the given map, mirroring GetState's
// historical make+copy so a snapshot always exposes an initialised map even
// when the live field is nil.
func cloneMap[K comparable, V any](m map[K]V) map[K]V {
	out := make(map[K]V, len(m))
	maps.Copy(out, m)
	return out
}

// ovnStateHolder guards the live OVNState. Every read and write goes through it,
// and Snapshot hands out a deep clone so readers never touch the guarded value
// directly. It must not be copied after first use (it embeds a mutex); the
// OVNClient that owns it is always used by pointer.
type ovnStateHolder struct {
	mu    sync.RWMutex
	state OVNState
}

// Snapshot returns a deep, lock-free copy of the current state.
func (h *ovnStateHolder) Snapshot() OVNState {
	h.mu.RLock()
	defer h.mu.RUnlock()
	return h.state.clone()
}

// Replace swaps in a freshly computed state. LocalChassisName is not part of a
// refresh — it is set once at connect time from the OS hostname — so when the
// caller leaves it empty it is carried over from the current state rather than
// being clobbered with the zero value.
func (h *ovnStateHolder) Replace(next OVNState) {
	h.mu.Lock()
	defer h.mu.Unlock()
	if next.LocalChassisName == "" {
		next.LocalChassisName = h.state.LocalChassisName
	}
	h.state = next
}

// SetLocalChassisName records the local chassis name (the OS hostname resolved
// at connect time). It is the only field mutated outside a full Replace.
func (h *ovnStateHolder) SetLocalChassisName(name string) {
	h.mu.Lock()
	defer h.mu.Unlock()
	h.state.LocalChassisName = name
}

// LocalChassisName returns the recorded local chassis name.
func (h *ovnStateHolder) LocalChassisName() string {
	h.mu.RLock()
	defer h.mu.RUnlock()
	return h.state.LocalChassisName
}

type OVNClient struct {
	sbClient ovsdbClient
	nbClient ovsdbClient
	state    ovnStateHolder
	cfg      Config

	onChange func() // callback when state changes

	// ready is set to true after Connect() completes initial setup.
	// Event handlers check this to avoid signalling refreshes before
	// both databases are connected and monitored. Atomic because cache
	// event handlers can read it from other goroutines while Connect()
	// is still completing setup.
	ready atomic.Bool

	// debounceCh receives signals from cache event handlers for tables that
	// should trigger a debounced state refresh. immediateCh receives signals
	// for chassisredirect changes that bypass debouncing for fast HA
	// failover. Both are buffered with capacity 1 so a storm of events
	// coalesces: at most one signal is queued, so the refresh loop runs at
	// most one in-flight pass plus one follow-up.
	debounceCh  chan struct{}
	immediateCh chan struct{}

	// drainWatchCh receives signals from the SB event handler on
	// chassisredirect Port_Binding changes. Unlike debounceCh/immediateCh it
	// does not feed the refresh loop; DrainGateways consumes it so the drain
	// wait re-checks countLocalCRPorts the moment a port migrates, instead of
	// waiting for the fixed safety re-poll. Buffered with capacity 1 so a
	// storm of events coalesces into at most one queued wake-up.
	drainWatchCh chan struct{}

	// loopDone is closed when refreshLoop exits. Set by Connect() before
	// starting the loop; nil before Connect() succeeds.
	loopDone chan struct{}

	// failoverObserved holds the first chassisredirect change observed in the
	// immediate-refresh path, or nil when no observation is pending. The
	// takeover reconcile consumes it via takeFailoverObservedAt to record the
	// failover-announce latency metric. Atomic because it is stamped from
	// cache event-handler goroutines and consumed by the reconcile loop.
	failoverObserved atomic.Pointer[failoverObservation]

	// refreshSeq numbers the refreshState passes. It is incremented at the
	// start of a pass and published as OVNState.Gen once that pass completes,
	// which is what orders a snapshot against a failover observation.
	refreshSeq atomic.Uint64
}

// failoverObservation is a chassisredirect change seen on the immediate-refresh
// path, awaiting the reconcile that announces the takeover routes.
type failoverObservation struct {
	// at is when the change was observed. It stays a time.Time rather than a
	// Unix nanosecond count so that it keeps its monotonic clock reading:
	// time.Since then subtracts on the monotonic clock, so an NTP step
	// between the observation and the announce — likely, since a gateway
	// reboot both triggers a takeover and steps the clock on startup —
	// cannot yield a negative or a wildly inflated sample.
	at time.Time

	// gen is the state generation current when the change was observed. Only
	// a refreshState pass that started afterwards reads the change out of the
	// cache, so only a snapshot with a higher Gen reflects it — and only that
	// snapshot's reconcile may consume the observation.
	gen uint64
}

func NewOVNClient(cfg Config, onChange func()) *OVNClient {
	return &OVNClient{
		cfg:          cfg,
		onChange:     onChange,
		debounceCh:   make(chan struct{}, 1),
		immediateCh:  make(chan struct{}, 1),
		drainWatchCh: make(chan struct{}, 1),
	}
}

func (o *OVNClient) Connect(ctx context.Context) error {
	hostname, err := getHostname()
	if err != nil {
		return fmt.Errorf("get hostname: %w", err)
	}
	o.state.SetLocalChassisName(hostname)

	slog.Info("connecting to OVN databases", "hostname", hostname)

	// On any error path, close partially-initialised clients so a retry
	// (agent.go retry loop) does not leak the previous connection by
	// overwriting o.sbClient / o.nbClient with a fresh one.
	success := false
	defer func() {
		if !success {
			o.closeClients()
		}
	}()

	reconnectBackoff := backoff.NewExponentialBackOff()

	// Connect to Southbound DB
	sbDBModel, err := sbDatabaseModel()
	if err != nil {
		return fmt.Errorf("create SB database model: %w", err)
	}

	sbOpts := []client.Option{
		client.WithReconnect(5*time.Second, reconnectBackoff),
		client.WithInactivityCheck(30*time.Second, 10*time.Second, reconnectBackoff),
	}
	for _, ep := range ovsdbEndpoints(o.cfg.OVNSBRemote) {
		sbOpts = append(sbOpts, client.WithEndpoint(ep))
	}
	if o.cfg.OVNTLS != nil {
		sbOpts = append(sbOpts, client.WithTLSConfig(o.cfg.OVNTLS))
	}
	o.sbClient, err = client.NewOVSDBClient(sbDBModel, sbOpts...)
	if err != nil {
		return fmt.Errorf("create SB client: %w", err)
	}

	if err := o.sbClient.Connect(ctx); err != nil {
		return fmt.Errorf("connect SB: %w", err)
	}
	slog.Info("connected to OVN SB", "remote", o.cfg.OVNSBRemote)
	setOVNConnectionState("sb", true)

	// Monitor SB tables
	o.sbClient.Cache().AddEventHandler(&sbEventHandler{ovn: o})

	sbMon := o.sbClient.NewMonitor(sbMonitorTables()...)
	if _, err := o.sbClient.Monitor(ctx, sbMon); err != nil {
		return fmt.Errorf("monitor SB: %w", err)
	}

	// Connect to Northbound DB
	nbDBModel, err := nbDatabaseModel()
	if err != nil {
		return fmt.Errorf("create NB database model: %w", err)
	}

	nbReconnectBackoff := backoff.NewExponentialBackOff()

	nbOpts := []client.Option{
		client.WithReconnect(5*time.Second, nbReconnectBackoff),
		client.WithInactivityCheck(30*time.Second, 10*time.Second, nbReconnectBackoff),
	}
	for _, ep := range ovsdbEndpoints(o.cfg.OVNNBRemote) {
		nbOpts = append(nbOpts, client.WithEndpoint(ep))
	}
	if o.cfg.OVNTLS != nil {
		nbOpts = append(nbOpts, client.WithTLSConfig(o.cfg.OVNTLS))
	}
	o.nbClient, err = client.NewOVSDBClient(nbDBModel, nbOpts...)
	if err != nil {
		return fmt.Errorf("create NB client: %w", err)
	}

	if err := o.nbClient.Connect(ctx); err != nil {
		return fmt.Errorf("connect NB: %w", err)
	}
	slog.Info("connected to OVN NB", "remote", o.cfg.OVNNBRemote)
	setOVNConnectionState("nb", true)

	// Monitor NB tables
	o.nbClient.Cache().AddEventHandler(&nbEventHandler{ovn: o})

	nbMon := o.nbClient.NewMonitor(nbMonitorTables()...)
	if _, err := o.nbClient.Monitor(ctx, nbMon); err != nil {
		return fmt.Errorf("monitor NB: %w", err)
	}

	// Mark as ready so event handlers can now signal refreshes.
	o.ready.Store(true)

	// Initial state refresh.
	o.refreshState(ctx)

	// Drain any signals queued by initial monitor events — refreshState
	// already captured the current state, so they would only cause
	// redundant work.
	o.drainSignals()

	// Start the refresh loop. It captures ctx via closure and exits when
	// ctx is cancelled. Close() waits for loopDone before tearing down
	// the OVSDB clients.
	o.loopDone = make(chan struct{})
	go func() {
		defer close(o.loopDone)
		o.refreshLoop(ctx)
	}()

	// Mirror each client's live connection status into the
	// ovn_connection_state gauge. Capture the client values now (not
	// o.sbClient/o.nbClient) so a concurrent closeClients() nil-ing the
	// fields cannot race the poller. The watcher shares refreshLoop's ctx,
	// which Run cancels before Close() runs, so it never outlives the client.
	go watchConnectionState(ctx, o.sbClient, o.nbClient, connStatePollInterval)

	success = true
	return nil
}

// connStatePollInterval is how often watchConnectionState samples each client's
// connection status. One second is fine-grained enough to catch a transient
// outage while adding negligible load.
const connStatePollInterval = time.Second

// watchConnectionState mirrors the live connection status of the SB and NB
// clients into the ovn_connection_state gauge until ctx is cancelled.
//
// The gauge is otherwise only cleared by closeClients(), so a transient OVSDB
// outage would never show in the metric: libovsdb's reconnect path
// re-establishes the monitors and repopulates the cache internally and only
// signals DisconnectNotify on a terminal (non-reconnect) close, so there is no
// event to hook for a drop-and-recover cycle. Polling Connected() is the only
// reliable mirror of the outage, which is what lets an operator alert on a lost
// OVN connection and what the reconnect integration scenario asserts on.
func watchConnectionState(ctx context.Context, sb, nb ovsdbClient, interval time.Duration) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			setOVNConnectionState("sb", sb.Connected())
			setOVNConnectionState("nb", nb.Connected())
		}
	}
}

func (o *OVNClient) Close() {
	// Stop new event handlers from signalling so closeClients can run
	// without further channel sends from cache callbacks.
	o.ready.Store(false)
	o.waitRefreshLoopStopped()
	o.closeClients()
}

// waitRefreshLoopStopped blocks until the refresh loop started by Connect has
// fully exited. After ctx is cancelled the loop may still be finishing one
// in-flight refreshState; the shutdown path calls this before its own
// post-drain refreshState so it becomes the sole writer of o.state and the two
// refreshes cannot interleave. It is a nil-safe receive on loopDone — safe when
// the loop was never started (port-forward-only mode) or has already exited.
func (o *OVNClient) waitRefreshLoopStopped() {
	if o.loopDone != nil {
		<-o.loopDone
	}
}

// closeClients closes both OVSDB clients (if set) and clears the references
// so a subsequent Connect() retry starts from a clean slate.
func (o *OVNClient) closeClients() {
	if o.sbClient != nil {
		o.sbClient.Close()
		o.sbClient = nil
		setOVNConnectionState("sb", false)
	}
	if o.nbClient != nil {
		o.nbClient.Close()
		o.nbClient = nil
		setOVNConnectionState("nb", false)
	}
}

// drainSignals empties both signal channels.
func (o *OVNClient) drainSignals() {
	select {
	case <-o.debounceCh:
	default:
	}
	select {
	case <-o.immediateCh:
	default:
	}
}

// GetState returns a deep snapshot of the current OVN state.
func (o *OVNClient) GetState() OVNState {
	return o.state.Snapshot()
}

// =============================================================================
// refreshState step helpers
// =============================================================================
//
// Each helper below is a pure function of the rows it is handed: no OVSDB
// client, no locking, no state mutation. refreshState reads the five tables and
// threads the intermediate maps through them in the documented order, which
// keeps the join's ordering invariants locally verifiable — every step can be
// unit-tested against a hand-built row set.

// chassisIndex builds the two chassis lookups the refresh needs:
// hostnameByRef resolves a Port_Binding.chassis reference (which may hold
// either the UUID or the name) to that chassis' hostname, and allChassisNames
// is the set of chassis short hostnames used for stale-chassis cleanup.
func chassisIndex(chassis []SBChassis) (hostnameByRef map[string]string, allChassisNames map[string]bool) {
	hostnameByRef = make(map[string]string, len(chassis)*2)
	allChassisNames = make(map[string]bool, len(chassis))
	for _, ch := range chassis {
		hostnameByRef[ch.UUID] = ch.Hostname
		hostnameByRef[ch.Name] = ch.Hostname
		// cleanupStaleChassis looks these keys up by the short chassis name
		// stamped on managed-route external_ids, so normalise FQDN SB
		// hostnames to the same leading label.
		allChassisNames[shortHostname(ch.Hostname)] = true
	}
	return hostnameByRef, allChassisNames
}

// localCRPorts returns the chassisredirect ports currently bound to this
// chassis, as a map of LRP name → chassisredirect logical_port name. When
// gatewayPort is set the scan is restricted to that single port.
//
// The LRP is resolved via crPortLRPName (options:distributed-port), not by
// slicing the port name.
func localCRPorts(
	portBindings []SBPortBinding,
	hostnameByRef map[string]string,
	localChassisName string,
	gatewayPort string,
) map[string]string {
	localLRPNames := make(map[string]string)
	for _, pb := range portBindings {
		if pb.Type != "chassisredirect" || pb.Chassis == nil || *pb.Chassis == "" {
			continue
		}
		// If gateway_port is configured, restrict to that single port.
		if gatewayPort != "" && pb.LogicalPort != gatewayPort {
			continue
		}
		if !hostnamesEqual(hostnameByRef[*pb.Chassis], localChassisName) {
			continue
		}
		if lrpName := crPortLRPName(pb); lrpName != "" {
			localLRPNames[lrpName] = pb.LogicalPort
		}
	}
	return localLRPNames
}

// crPortLRPName returns the name of the distributed Logical_Router_Port that a
// chassisredirect Port_Binding redirects for.
//
// ovn-northd records the answer in options:distributed-port — that is the
// schema-backed join, and it is what this reads. The "cr-<LRP>" name form is
// only an ovn-northd/Neutron naming convention, not a schema guarantee, so it
// is kept as a warned fallback for rows that predate (or diverge from) the
// option. A row with neither yields "" and is skipped by the caller rather than
// silently mapping to a bogus LRP.
func crPortLRPName(pb SBPortBinding) string {
	if lrp := pb.Options["distributed-port"]; lrp != "" {
		return lrp
	}
	if strings.HasPrefix(pb.LogicalPort, "cr-") {
		lrp := strings.TrimPrefix(pb.LogicalPort, "cr-")
		slog.Warn("chassisredirect port has no options:distributed-port, falling back to the cr- name convention",
			"logical_port", pb.LogicalPort, "lrp", lrp)
		return lrp
	}
	slog.Warn("cannot resolve the LRP of a chassisredirect port: no options:distributed-port and no cr- prefix, skipping",
		"logical_port", pb.LogicalPort)
	return ""
}

// segmentsByLRP resolves each local LRP's localnet segment. A gateway LRP's
// peer logical switch (the external network) carries a localnet port whose SB
// Port_Binding holds the physnet name (options:network_name) and the optional
// VLAN tag. Two joins over the Port_Binding table: localnet rows indexed by
// datapath, then the switch-side patch rows (options:peer == LRP name) sharing
// that datapath. Deliberately no neutron:device_owner filter: the join must
// also work for non-Neutron topologies (e.g. the E2E lab) that set no
// external_ids.
func segmentsByLRP(portBindings []SBPortBinding, localLRPNames map[string]string) map[string]*LocalnetSegment {
	localnetByDatapath := make(map[string]SBPortBinding)
	for _, pb := range portBindings {
		if pb.Type == "localnet" {
			localnetByDatapath[pb.Datapath] = pb
		}
	}
	segmentByLRP := make(map[string]*LocalnetSegment)
	for _, pb := range portBindings {
		if pb.Type != "patch" {
			continue
		}
		peer := pb.Options["peer"]
		if peer == "" {
			continue
		}
		if _, isLocal := localLRPNames[peer]; !isLocal {
			continue
		}
		ln, ok := localnetByDatapath[pb.Datapath]
		if !ok {
			continue
		}
		seg := &LocalnetSegment{
			LocalnetPort: ln.LogicalPort,
			NetworkName:  ln.Options["network_name"],
		}
		if ln.Tag != nil {
			tag := *ln.Tag
			seg.VLANTag = &tag
		}
		segmentByLRP[peer] = seg
	}
	return segmentByLRP
}

// lrpIndex bundles the two Logical_Router_Port lookups the router join needs.
type lrpIndex struct {
	byName map[string]NBLogicalRouterPort
	byUUID map[string]NBLogicalRouterPort
}

// indexLRPs indexes the NB Logical_Router_Port rows by name and UUID.
func indexLRPs(lrps []NBLogicalRouterPort) lrpIndex {
	idx := lrpIndex{
		byName: make(map[string]NBLogicalRouterPort, len(lrps)),
		byUUID: make(map[string]NBLogicalRouterPort, len(lrps)),
	}
	for _, lrp := range lrps {
		idx.byName[lrp.Name] = lrp
		idx.byUUID[lrp.UUID] = lrp
	}
	return idx
}

// localLRPUUIDSet resolves the locally-active LRP names to their NB UUIDs.
// Names with no matching LRP row are dropped.
func localLRPUUIDSet(localLRPNames map[string]string, idx lrpIndex) map[string]bool {
	uuids := make(map[string]bool, len(localLRPNames))
	for lrpName := range localLRPNames {
		if lrp, ok := idx.byName[lrpName]; ok {
			uuids[lrp.UUID] = true
		}
	}
	return uuids
}

// collectLocalRouters finds the routers that own a locally-active LRP.
// Alongside the router list it returns the two NAT-UUID indexes the NAT step
// consumes: natUUIDToRouterMAC maps each NAT UUID to the MAC of the router port
// that owns it (so hairpin flows can set the correct dl_dst), and
// natUUIDToSegment records the owning router's localnet segment (so per-IP
// state lands on the right patch port/interface).
func collectLocalRouters(
	routers []NBLogicalRouter,
	idx lrpIndex,
	localLRPUUIDs map[string]bool,
	localLRPNames map[string]string,
	segmentByLRP map[string]*LocalnetSegment,
) (localRouters []LocalRouterInfo, natUUIDToRouterMAC, natUUIDToSegment map[string]string) {
	natUUIDToRouterMAC = make(map[string]string)
	natUUIDToSegment = make(map[string]string)
	for _, router := range routers {
		var matchedLRP *NBLogicalRouterPort
		for _, portUUID := range router.Ports {
			if localLRPUUIDs[portUUID] {
				lrp := idx.byUUID[portUUID]
				matchedLRP = &lrp
				break
			}
		}
		if matchedLRP == nil {
			continue
		}
		segment := segmentByLRP[matchedLRP.Name]
		localRouters = append(localRouters, LocalRouterInfo{
			RouterName:          router.Name,
			RouterUUID:          router.UUID,
			LRPName:             matchedLRP.Name,
			LRPUUID:             matchedLRP.UUID,
			LRPMAC:              matchedLRP.MAC,
			LRPNetworks:         matchedLRP.Networks,
			CRPort:              localLRPNames[matchedLRP.Name],
			Segment:             segment,
			GatewayChassisUUIDs: matchedLRP.GatewayChassis,
		})
		for _, natUUID := range router.Nat {
			if matchedLRP.MAC != "" {
				natUUIDToRouterMAC[natUUID] = matchedLRP.MAC
			}
			if segment != nil {
				natUUIDToSegment[natUUID] = segment.LocalnetPort
			}
		}
	}
	return localRouters, natUUIDToRouterMAC, natUUIDToSegment
}

// discoverLRPNetworks extracts the deduplicated network CIDRs of the
// locally-active LRPs. A malformed CIDR is warned about and skipped.
func discoverLRPNetworks(localRouters []LocalRouterInfo) []*net.IPNet {
	var discoveredNets []*net.IPNet
	for _, lr := range localRouters {
		for _, ns := range lr.LRPNetworks {
			_, cidr, err := net.ParseCIDR(ns)
			if err != nil {
				slog.Warn("failed to parse LRP network", "network", ns, "router", lr.RouterName, "error", err)
				continue
			}
			discoveredNets = append(discoveredNets, cidr)
		}
	}
	return uniqueNetworks(discoveredNets)
}

// natCollection accumulates the NAT-derived state. Steps 5 (NB NAT rows) and 5b
// (SB gateway NatAddresses) both feed the same three outputs, so they share one
// accumulator rather than threading three parallel maps by hand.
//
// FIPCount tracks the dnat_and_snat entries purely so the state-updated log line
// can report them; no downstream consumer reads the FIP list itself.
type natCollection struct {
	FIPCount      int
	SNATIPs       []string
	IPToRouterMAC map[string]string
	IPToSegment   map[string]string
}

func newNATCollection() *natCollection {
	return &natCollection{
		IPToRouterMAC: make(map[string]string),
		IPToSegment:   make(map[string]string),
	}
}

// addNBNATs folds the NB NAT rows of locally-active routers into nc (step 5).
// Rows whose NAT UUID is not owned by a local router are ignored.
func (nc *natCollection) addNBNATs(
	nats []NBNAT,
	natUUIDToRouterMAC, natUUIDToSegment map[string]string,
	filters []*net.IPNet,
) {
	for _, nat := range nats {
		routerMAC, ok := natUUIDToRouterMAC[nat.UUID]
		if !ok {
			continue
		}
		ip := nat.ExternalIP
		// Validate every external IP unconditionally: a malformed row must
		// die here at ingest, regardless of whether a filter is in effect, so
		// it can never reach an nft/FRR/kernel command payload downstream.
		parsedIP := net.ParseIP(ip)
		if parsedIP == nil {
			slog.Warn("skipping NAT entry with invalid external IP",
				"external_ip", ip, "nat", nat.UUID, "type", nat.Type)
			continue
		}
		if len(filters) > 0 && !containedInAny(parsedIP, filters) {
			continue
		}
		nc.IPToRouterMAC[ip] = routerMAC
		if seg, ok := natUUIDToSegment[nat.UUID]; ok {
			nc.IPToSegment[ip] = seg
		}
		switch nat.Type {
		case "dnat_and_snat":
			nc.FIPCount++
		case "snat":
			// SNATIPs feeds the IPv4-only nft masquerade set (buildNftRuleset's
			// "table ip"), so keep IPv6 out until full v6 support (#85/#70)
			// lands. The dual-stack IPToRouterMAC above still carries the
			// address for the family-aware OVS hairpin plane (#54).
			if parsedIP.To4() != nil {
				nc.SNATIPs = append(nc.SNATIPs, ip)
			} else {
				slog.Debug("excluding non-IPv4 SNAT external IP from the nft masquerade set, IPv6 support tracked in #85/#70",
					"external_ip", ip)
			}
		}
	}
}

// addSBGatewayNATAddresses folds the SB gateway port NatAddresses into nc
// (step 5b). When a router has an external gateway but no connected internal
// subnets, Neutron has not yet created the NB NAT entry — yet the SB
// Port_Binding for the gateway patch port already carries the NAT IP in its
// NatAddresses field. Extracting these announces routes as soon as the gateway
// is set.
func (nc *natCollection) addSBGatewayNATAddresses(
	portBindings []SBPortBinding,
	localLRPNames map[string]string,
	idx lrpIndex,
	segmentByLRP map[string]*LocalnetSegment,
	filters []*net.IPNet,
) {
	for _, pb := range portBindings {
		if pb.Type != "patch" {
			continue
		}
		peer := pb.Options["peer"]
		if peer == "" {
			continue
		}
		if _, isLocal := localLRPNames[peer]; !isLocal {
			continue
		}
		if pb.ExternalIDs["neutron:device_owner"] != "network:router_gateway" {
			continue
		}
		routerMAC := idx.byName[peer].MAC
		for _, natAddr := range pb.NatAddresses {
			for _, ip := range parseNatAddressIPs(natAddr) {
				// parseNatAddressIPs only yields net.ParseIP-valid addresses;
				// re-parse here so the filter and family gate apply to every
				// candidate regardless of whether a filter is in effect.
				parsedIP := net.ParseIP(ip)
				if len(filters) > 0 && !containedInAny(parsedIP, filters) {
					continue
				}
				// Keep IPv6 out of the IPv4-only nft masquerade set (#85/#70)
				// while still tracking it for the OVS hairpin plane (#54).
				if parsedIP.To4() != nil {
					nc.SNATIPs = append(nc.SNATIPs, ip)
				} else {
					slog.Debug("excluding non-IPv4 SB SNAT address from the nft masquerade set, IPv6 support tracked in #85/#70",
						"external_ip", ip)
				}
				if routerMAC != "" {
					nc.IPToRouterMAC[ip] = routerMAC
				}
				if seg := segmentByLRP[peer]; seg != nil {
					nc.IPToSegment[ip] = seg.LocalnetPort
				}
			}
		}
	}
}

// refreshState performs a unified state refresh from both OVN databases.
// It determines which routers are locally active and collects their NAT entries.
//
// Mapping chain:
//
//	SB chassisredirect (logical_port="cr-lrp-X", chassis=local?)
//	  → NB Logical_Router_Port (name="lrp-X")
//	  → NB Logical_Router (ports ⊇ {LRP UUID}, nat = {NAT UUIDs})
//	  → NB NAT (external_ip)
//
// Every table is read through cachedList, which falls back to a direct server
// select when the monitor cache is missing rows or holds a stale column (see
// ovn_cache.go). The per-step joins themselves are the pure helpers above; this
// function only sequences them and publishes the result.
func (o *OVNClient) refreshState(ctx context.Context) {
	// Number this pass before the first cache read. An observation stamped
	// while the reads below are already in flight must not be consumed by the
	// state this pass publishes: those reads may have passed the changed row
	// already, so the resulting snapshot need not reflect the change.
	seq := o.refreshSeq.Add(1)

	// Step 1: chassisredirect port bindings and chassis hostnames.
	portBindings, err := cachedList(ctx, o.sbClient, "Port_Binding",
		pbCheckColumns, keyOfSBPortBinding, decodeSBPortBinding)
	if err != nil {
		slog.Error("failed to list port bindings", "error", err)
		return
	}
	chassis, err := cachedList(ctx, o.sbClient, "Chassis",
		chCheckColumns, keyOfSBChassis, decodeSBChassis)
	if err != nil {
		slog.Error("failed to list chassis", "error", err)
		return
	}
	hostnameByRef, allChassisNames := chassisIndex(chassis)
	localLRPNames := localCRPorts(portBindings, hostnameByRef,
		o.state.LocalChassisName(), o.cfg.GatewayPort)

	// Step 1b: resolve each local LRP's localnet segment.
	segmentByLRP := segmentsByLRP(portBindings, localLRPNames)

	// Step 2: index the NB logical router ports.
	lrps, err := cachedList(ctx, o.nbClient, "Logical_Router_Port",
		lrpCheckColumns, keyOfNBLogicalRouterPort, decodeNBLogicalRouterPort)
	if err != nil {
		slog.Error("failed to list logical router ports", "error", err)
		return
	}
	idx := indexLRPs(lrps)
	localLRPUUIDs := localLRPUUIDSet(localLRPNames, idx)

	// Step 3: find the routers that own a locally-active LRP.
	routers, err := cachedList(ctx, o.nbClient, "Logical_Router",
		lrCheckColumns, keyOfNBLogicalRouter, decodeNBLogicalRouter)
	if err != nil {
		slog.Error("failed to list logical routers", "error", err)
		return
	}
	localRouters, natUUIDToRouterMAC, natUUIDToSegment := collectLocalRouters(
		routers, idx, localLRPUUIDs, localLRPNames, segmentByLRP)

	// Step 4: derive the network CIDRs, then the effective filters. Manual
	// config takes precedence over auto-discovery.
	discoveredNets := discoverLRPNetworks(localRouters)
	effectiveFilters := effectiveNetworkFilters(o.cfg.NetworkFilters, discoveredNets)

	// Step 5 + 5b: collect the NAT external IPs of the locally-active routers,
	// from NB NAT rows and from the SB gateway port NatAddresses.
	nats, err := cachedList(ctx, o.nbClient, "NAT",
		natCheckColumns, keyOfNBNAT, decodeNBNAT)
	if err != nil {
		slog.Error("failed to list NAT entries", "error", err)
		return
	}
	nc := newNATCollection()
	nc.addNBNATs(nats, natUUIDToRouterMAC, natUUIDToSegment, effectiveFilters)
	nc.addSBGatewayNATAddresses(portBindings, localLRPNames, idx, segmentByLRP, effectiveFilters)

	// Step 6: Update state atomically. Replace preserves LocalChassisName
	// (set once at connect time), so the refresh never needs to re-read or
	// re-supply it.
	o.state.Replace(OVNState{
		LocalRouters:       localRouters,
		HasLocalRouters:    len(localRouters) > 0,
		SNATIPs:            nc.SNATIPs,
		NATIPToRouterMAC:   nc.IPToRouterMAC,
		NATIPToSegment:     nc.IPToSegment,
		DiscoveredNetworks: discoveredNets,
		AllChassisNames:    allChassisNames,
		Gen:                seq,
	})

	slog.Info("state updated",
		"local_routers", len(localRouters),
		"fips", nc.FIPCount,
		"snat_ips", len(nc.SNATIPs),
		"discovered_networks", len(discoveredNets),
	)
	for _, lr := range localRouters {
		slog.Debug("locally active router",
			"router", lr.RouterName,
			"lrp", lr.LRPName,
			"cr_port", lr.CRPort,
			"segment", segmentName(lr.Segment),
		)
	}
}

// refreshLoop is the OVN client's event loop. It receives signals from cache
// event handlers and runs state refreshes with appropriate debouncing.
// Started by Connect() and runs until ctx is cancelled.
//
//   - debounceCh signals coalesce into one refresh per eventDebounceInterval,
//     followed by an onChange callback debounced by reconcileDebounceInterval.
//   - immediateCh signals bypass debouncing and trigger an immediate refresh +
//     onChange. A pending debounce timer is cancelled because the immediate
//     refresh supersedes it.
//
// Signal channels have capacity 1, and the loop processes signals
// sequentially, so a storm of events produces at most one in-flight pass
// plus one queued follow-up.
func (o *OVNClient) refreshLoop(ctx context.Context) {
	var (
		debounceTimer  *time.Timer
		debounceFire   <-chan time.Time
		reconcileTimer *time.Timer
		reconcileFire  <-chan time.Time
	)

	for {
		select {
		case <-ctx.Done():
			if debounceTimer != nil {
				debounceTimer.Stop()
			}
			if reconcileTimer != nil {
				reconcileTimer.Stop()
			}
			return

		case <-o.debounceCh:
			if debounceTimer == nil {
				debounceTimer = time.NewTimer(eventDebounceInterval)
				debounceFire = debounceTimer.C
			}

		case <-debounceFire:
			debounceTimer = nil
			debounceFire = nil
			o.refreshState(ctx)
			if reconcileTimer == nil && o.onChange != nil {
				reconcileTimer = time.NewTimer(reconcileDebounceInterval)
				reconcileFire = reconcileTimer.C
			}

		case <-reconcileFire:
			reconcileTimer = nil
			reconcileFire = nil
			if o.onChange != nil {
				o.onChange()
			}

		case <-o.immediateCh:
			// Immediate supersedes any pending debounce: refresh now and
			// invoke onChange directly to bypass reconcile debouncing.
			if debounceTimer != nil {
				debounceTimer.Stop()
				debounceTimer = nil
				debounceFire = nil
			}
			o.refreshState(ctx)
			if o.onChange != nil {
				o.onChange()
			}
		}
	}
}

// debounceStateRefresh signals the refresh loop to schedule a debounced state
// refresh. Concurrent calls coalesce: at most one signal is queued.
func (o *OVNClient) debounceStateRefresh() {
	if !o.ready.Load() {
		return // not fully connected yet
	}
	select {
	case o.debounceCh <- struct{}{}:
	default:
		// already queued
	}
}

// immediateStateRefresh signals the refresh loop to run a state refresh
// immediately, bypassing debouncing. Used for chassisredirect changes to
// minimise HA failover reaction time. Concurrent calls coalesce: at most
// one signal is queued, so a burst of events results in at most one
// in-flight pass plus one queued follow-up.
func (o *OVNClient) immediateStateRefresh() {
	if !o.ready.Load() {
		return // not fully connected yet
	}
	// Stamp the first chassisredirect observation of this failover window so
	// the takeover reconcile can measure the announce latency. The cache has
	// already applied the change by the time the event handler runs, so any
	// refreshState pass numbered above refreshSeq reads it. CompareAndSwap
	// keeps the earliest observation; takeFailoverObservedAt clears the slot
	// once a reconcile that reflects the change has consumed it.
	o.failoverObserved.CompareAndSwap(nil, &failoverObservation{
		at:  time.Now(),
		gen: o.refreshSeq.Load(),
	})
	select {
	case o.immediateCh <- struct{}{}:
	default:
		// already queued
	}
}

// signalDrainWatch wakes a DrainGateways poll waiting for chassisredirect
// ports to migrate away. It is fired from the SB event handler on every
// chassisredirect Port_Binding change so the drain re-checks countLocalCRPorts
// the moment OVN rebinds a port, instead of waiting for the fixed safety
// re-poll. Concurrent calls coalesce: at most one wake-up is queued. Outside a
// drain nothing reads the channel, so the queued signal is simply harmless.
func (o *OVNClient) signalDrainWatch() {
	if !o.ready.Load() {
		return // not fully connected yet
	}
	select {
	case o.drainWatchCh <- struct{}{}:
	default:
		// already queued
	}
}

// takeFailoverObservedAt consumes the chassisredirect observation stamped by
// immediateStateRefresh and returns when the change was seen, or the zero Time
// when nothing is pending.
//
// snapGen is OVNState.Gen of the caller's own snapshot. An observation is only
// consumed by a snapshot that already reflects it (snapGen > gen). Without that
// check the observation would go to whichever reconcile ran first, which is not
// necessarily the one that announces: a debounce cycle refreshes state, arms its
// reconcile timer, and a chassisredirect change landing inside that window is
// then consumed — and discarded — by a reconcile still holding the pre-failover
// snapshot, leaving the genuine takeover reconcile that follows with nothing to
// measure.
//
// A snapshot that does reflect the change consumes the observation whether or
// not it goes on to announce. That keeps the lifetime bounded to one failover
// window: the event handler stamps on every chassis, not just the takeover
// target, so an observation left pending on a standby would otherwise attach
// itself to some unrelated announce minutes later.
//
// Only the reconcile loop consumes, and it is serial, so clearing the slot
// cannot drop a competing observation — immediateStateRefresh only ever stamps
// into an empty one.
func (o *OVNClient) takeFailoverObservedAt(snapGen uint64) time.Time {
	obs := o.failoverObserved.Load()
	if obs == nil || snapGen <= obs.gen {
		return time.Time{}
	}
	o.failoverObserved.Store(nil)
	return obs.at
}

// =============================================================================
// SB event handler (implements cache.EventHandler)
// =============================================================================

type sbEventHandler struct {
	ovn *OVNClient
}

func (h *sbEventHandler) OnAdd(table string, m model.Model) {
	if h.isChassisRedirect(table, m) {
		slog.Debug("chassisredirect port added, immediate refresh")
		h.ovn.signalDrainWatch()
		h.ovn.immediateStateRefresh()
		return
	}
	h.handleChange(table)
}

func (h *sbEventHandler) OnUpdate(table string, old, updated model.Model) {
	if h.isChassisRedirect(table, updated) && h.chassisRebound(old, updated) {
		slog.Debug("chassisredirect port rebound, immediate refresh")
		h.ovn.signalDrainWatch()
		h.ovn.immediateStateRefresh()
		return
	}
	h.handleChange(table)
}

func (h *sbEventHandler) OnDelete(table string, m model.Model) {
	if h.isChassisRedirect(table, m) {
		slog.Debug("chassisredirect port deleted, immediate refresh")
		h.ovn.signalDrainWatch()
		h.ovn.immediateStateRefresh()
		return
	}
	h.handleChange(table)
}

func (h *sbEventHandler) isChassisRedirect(table string, m model.Model) bool {
	if table != "Port_Binding" {
		return false
	}
	pb, ok := m.(*SBPortBinding)
	return ok && pb.Type == "chassisredirect"
}

// chassisRebound reports whether a Port_Binding update moved the row to a
// different chassis, which is what a gateway re-election looks like on the
// wire.
//
// The SB monitor selects whole tables, so OnUpdate fires for every column of a
// chassisredirect row, not just chassis. refreshState reads only Type and
// Chassis from such a row, so an update that leaves Chassis alone — northd
// rewriting nat_addresses because an operator added a FIP, say — changes
// nothing this agent derives and is not a failover. Those updates take the
// debounced path: routing them through the immediate path would stamp a
// failover observation, and the sub-second announce that follows (no
// re-election to wait for) would land in failover_announce_seconds. FIP churn
// outnumbers failovers by orders of magnitude, so the histogram would sit in
// the fast buckets and a p95 alert would stay quiet through a slow takeover.
//
// A pair that is not two Port_Binding rows cannot be compared; treat it as a
// rebinding rather than risk missing a real failover.
func (h *sbEventHandler) chassisRebound(old, updated model.Model) bool {
	oldPB, oldOK := old.(*SBPortBinding)
	newPB, newOK := updated.(*SBPortBinding)
	if !oldOK || !newOK {
		return true
	}
	return chassisRef(oldPB) != chassisRef(newPB)
}

// chassisRef returns a Port_Binding's chassis reference, collapsing the unset
// pointer and the empty string — both mean "bound nowhere" to refreshState.
func chassisRef(pb *SBPortBinding) string {
	if pb.Chassis == nil {
		return ""
	}
	return *pb.Chassis
}

func (h *sbEventHandler) handleChange(table string) {
	slog.Debug("SB change detected", "table", table)
	if table == "Port_Binding" || table == "Chassis" {
		h.ovn.debounceStateRefresh()
	}
}

// =============================================================================
// NB event handler (implements cache.EventHandler)
// =============================================================================

type nbEventHandler struct {
	ovn *OVNClient
}

func (h *nbEventHandler) OnAdd(table string, m model.Model) {
	h.handleChange(table)
}

func (h *nbEventHandler) OnUpdate(table string, old, updated model.Model) {
	h.handleChange(table)
}

func (h *nbEventHandler) OnDelete(table string, m model.Model) {
	h.handleChange(table)
}

func (h *nbEventHandler) handleChange(table string) {
	slog.Debug("NB change detected", "table", table)
	switch table {
	case "NAT", "Logical_Router", "Logical_Router_Port":
		h.ovn.debounceStateRefresh()
	case "Gateway_Chassis":
		// refreshState does not read Gateway_Chassis, but a priority change
		// must still wake the agent: the reconcile that follows the refresh
		// runs EnsureActivePriorityLead, which is how the active chassis
		// reacts to a peer draining (priority→0), restoring (→1) or
		// boosting. Without this trigger a peer's drain/restore is invisible
		// until the 60s periodic reconcile — long enough for a priority tie
		// to leave ovn-northd flapping the chassisredirect port and
		// stranding the FIPs. Rapid stop/start cycles are bursts of
		// Gateway_Chassis writes, which is why the hang is worst under quick
		// succession.
		h.ovn.debounceStateRefresh()
	}
}

// =============================================================================
// Helpers
// =============================================================================

// sbDatabaseModel and nbDatabaseModel register exactly the tables the agent
// reads or writes. They are deliberately NOT the generated FullDatabaseModel():
// registering every table would widen connect-time schema validation to columns
// the agent never touches, so an unrelated OVN schema change could refuse the
// connection outright.
func sbDatabaseModel() (model.ClientDBModel, error) {
	return model.NewClientDBModel("OVN_Southbound", map[string]model.Model{
		"Port_Binding": &SBPortBinding{},
		"Chassis":      &SBChassis{},
	})
}

func nbDatabaseModel() (model.ClientDBModel, error) {
	return model.NewClientDBModel("OVN_Northbound", map[string]model.Model{
		"NAT":                         &NBNAT{},
		"Logical_Router":              &NBLogicalRouter{},
		"Logical_Router_Port":         &NBLogicalRouterPort{},
		"Logical_Router_Static_Route": &NBLogicalRouterStaticRoute{},
		"Static_MAC_Binding":          &NBStaticMACBinding{},
		"Gateway_Chassis":             &NBGatewayChassis{},
	})
}

// sbMonitorTables and nbMonitorTables project each monitored table down to the
// columns the agent actually consumes.
//
// The projection is mandatory, not an optimisation. A generated model carries
// every column of its table, and an unprojected WithTable monitors all of them:
// Chassis.nb_cfg is bumped by ovn-northd on every processing round, so
// monitoring it would fire a cache event — and therefore a state refresh — on a
// cadence that has nothing to do with the agent's inputs, storming the debounce
// loop on an otherwise idle cluster. Listing the columns explicitly also keeps
// the monitor honest: the set below is exactly what refreshState, the cache
// consistency guard (see the *CheckColumns in ovn_cache.go) and the gateway
// writers read.
func sbMonitorTables() []client.MonitorOption {
	pb := SBPortBinding{}
	ch := SBChassis{}
	return []client.MonitorOption{
		client.WithTable(&pb,
			&pb.LogicalPort,  // chassisredirect / patch / localnet port name
			&pb.Type,         // row kind: chassisredirect, patch, localnet
			&pb.Chassis,      // which chassis owns a chassisredirect port
			&pb.Datapath,     // localnet ↔ patch join key
			&pb.Tag,          // VLAN tag of a localnet segment
			&pb.Options,      // distributed-port, peer, network_name
			&pb.ExternalIDs,  // neutron:device_owner (router-gateway filter)
			&pb.NatAddresses, // SB-side SNAT addresses of a gateway port
		),
		client.WithTable(&ch,
			&ch.Name,     // chassis reference form used by Port_Binding.chassis
			&ch.Hostname, // maps a chassis to this host
			// Deliberately NOT nb_cfg: northd bumps it every round.
		),
	}
}

func nbMonitorTables() []client.MonitorOption {
	nat := NBNAT{}
	lr := NBLogicalRouter{}
	lrp := NBLogicalRouterPort{}
	lrsr := NBLogicalRouterStaticRoute{}
	smb := NBStaticMACBinding{}
	gwc := NBGatewayChassis{}
	return []client.MonitorOption{
		client.WithTable(&nat,
			&nat.Type,       // dnat_and_snat vs snat
			&nat.ExternalIP, // the FIP / SNAT address itself
		),
		client.WithTable(&lr,
			&lr.Name,
			&lr.Ports,        // → Logical_Router_Port
			&lr.Nat,          // → NAT
			&lr.StaticRoutes, // → Logical_Router_Static_Route (managed routes)
		),
		client.WithTable(&lrp,
			&lrp.Name,
			&lrp.MAC,            // hairpin dl_dst
			&lrp.Networks,       // discovered provider networks
			&lrp.GatewayChassis, // → Gateway_Chassis (HA group join)
		),
		client.WithTable(&lrsr,
			&lrsr.IPPrefix,
			&lrsr.Nexthop,
			&lrsr.OutputPort,
			&lrsr.ExternalIDs, // agent-managed marker + takeover marker
		),
		client.WithTable(&smb,
			&smb.LogicalPort,
			&smb.IP,
			&smb.MAC,
		),
		client.WithTable(&gwc,
			&gwc.Name,
			&gwc.ChassisName,
			&gwc.Priority, // the anti-flapping lead
		),
	}
}

func ovsdbEndpoints(remote string) []string {
	parts := strings.Split(remote, ",")
	var endpoints []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			endpoints = append(endpoints, p)
		}
	}
	return endpoints
}

// uniqueNetworks deduplicates and sorts a list of *net.IPNet by string representation.
func uniqueNetworks(nets []*net.IPNet) []*net.IPNet {
	seen := make(map[string]bool, len(nets))
	var result []*net.IPNet
	for _, n := range nets {
		key := n.String()
		if !seen[key] {
			seen[key] = true
			result = append(result, n)
		}
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].String() < result[j].String()
	})
	return result
}

// parseNatAddressIPs extracts IP addresses from an OVN NatAddresses entry.
// Format: "MAC IP1 [IP2 ...] [is_chassis_resident("port")]"
func parseNatAddressIPs(natAddr string) []string {
	fields := strings.Fields(natAddr)
	if len(fields) < 2 {
		return nil
	}
	var ips []string
	for _, f := range fields[1:] {
		if strings.HasPrefix(f, "is_chassis_resident") {
			break
		}
		if net.ParseIP(f) != nil {
			ips = append(ips, f)
		}
	}
	return ips
}

func getHostname() (string, error) {
	h, err := os.Hostname()
	if err != nil {
		return "", err
	}
	return shortHostname(h), nil
}

// shortHostname returns the leading DNS label of a hostname. SB Chassis
// hostnames are often FQDNs while the agent's own hostname (getHostname) is
// domain-stripped, so any comparison between the two must first reduce both to
// this label. Casing is preserved: both sides ultimately derive from the same
// OS hostname, so a naive strip keeps them comparable while hostnamesEqual
// still guards against incidental case drift.
func shortHostname(h string) string {
	if idx := strings.IndexByte(h, '.'); idx != -1 {
		h = h[:idx]
	}
	return h
}

// hostnamesEqual reports whether two chassis hostnames name the same host. It
// compares only the leading DNS label, case-insensitively, so an FQDN SB
// hostname matches the agent's domain-stripped local hostname regardless of
// case. This is the single seam for chassis-hostname matching.
func hostnamesEqual(a, b string) bool {
	return strings.EqualFold(shortHostname(a), shortHostname(b))
}
