// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const AddressSetTable = "Address_Set"

// AddressSet defines an object in Address_Set table
type AddressSet struct {
	UUID      string   `ovsdb:"_uuid"`
	Addresses []string `ovsdb:"addresses" validate:"dive,max=9223372036854775806"`
	Name      string   `ovsdb:"name" validate:"max=9223372036854775806"`
}
