// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const ChassisTable = "Chassis"

// Chassis defines an object in Chassis table
type Chassis struct {
	UUID                string            `ovsdb:"_uuid"`
	Encaps              []string          `ovsdb:"encaps" validate:"min=1"`
	ExternalIDs         map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Hostname            string            `ovsdb:"hostname" validate:"max=9223372036854775806"`
	Name                string            `ovsdb:"name" validate:"max=9223372036854775806"`
	NbCfg               int               `ovsdb:"nb_cfg" validate:"max=9223372036854775806"`
	OtherConfig         map[string]string `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	TransportZones      []string          `ovsdb:"transport_zones" validate:"dive,max=9223372036854775806"`
	VtepLogicalSwitches []string          `ovsdb:"vtep_logical_switches" validate:"dive,max=9223372036854775806"`
}
