// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const ChassisPrivateTable = "Chassis_Private"

// ChassisPrivate defines an object in Chassis_Private table
type ChassisPrivate struct {
	UUID           string            `ovsdb:"_uuid"`
	Chassis        *string           `ovsdb:"chassis"`
	ExternalIDs    map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Name           string            `ovsdb:"name" validate:"max=9223372036854775806"`
	NbCfg          int               `ovsdb:"nb_cfg" validate:"max=9223372036854775806"`
	NbCfgTimestamp int               `ovsdb:"nb_cfg_timestamp" validate:"max=9223372036854775806"`
}
