// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const DNSTable = "DNS"

// DNS defines an object in DNS table
type DNS struct {
	UUID        string            `ovsdb:"_uuid"`
	Datapaths   []string          `ovsdb:"datapaths" validate:"min=1"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Options     map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Records     map[string]string `ovsdb:"records" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
}
