// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const EncapTable = "Encap"

type (
	EncapType = string
)

var (
	EncapTypeGeneve EncapType = "geneve"
	EncapTypeSTT    EncapType = "stt"
	EncapTypeVxlan  EncapType = "vxlan"
)

// Encap defines an object in Encap table
type Encap struct {
	UUID        string            `ovsdb:"_uuid"`
	ChassisName string            `ovsdb:"chassis_name" validate:"max=9223372036854775806"`
	IP          string            `ovsdb:"ip" validate:"max=9223372036854775806"`
	Options     map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Type        EncapType         `ovsdb:"type" validate:"max=9223372036854775806,oneof='geneve' 'stt' 'vxlan'"`
}
