// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const HAChassisTable = "HA_Chassis"

// HAChassis defines an object in HA_Chassis table
type HAChassis struct {
	UUID        string            `ovsdb:"_uuid"`
	Chassis     *string           `ovsdb:"chassis"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Priority    int               `ovsdb:"priority" validate:"min=0,max=32767"`
}
