// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const IGMPGroupTable = "IGMP_Group"

// IGMPGroup defines an object in IGMP_Group table
type IGMPGroup struct {
	UUID        string   `ovsdb:"_uuid"`
	Address     string   `ovsdb:"address" validate:"max=9223372036854775806"`
	Chassis     *string  `ovsdb:"chassis"`
	ChassisName string   `ovsdb:"chassis_name" validate:"max=9223372036854775806"`
	Datapath    *string  `ovsdb:"datapath"`
	Ports       []string `ovsdb:"ports"`
	Protocol    string   `ovsdb:"protocol" validate:"max=9223372036854775806"`
}
