// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const IPMulticastTable = "IP_Multicast"

// IPMulticast defines an object in IP_Multicast table
type IPMulticast struct {
	UUID          string `ovsdb:"_uuid"`
	Datapath      string `ovsdb:"datapath"`
	Enabled       *bool  `ovsdb:"enabled"`
	EthSrc        string `ovsdb:"eth_src" validate:"max=9223372036854775806"`
	IdleTimeout   *int   `ovsdb:"idle_timeout" validate:"omitempty,max=9223372036854775806"`
	Ip4Src        string `ovsdb:"ip4_src" validate:"max=9223372036854775806"`
	Ip6Src        string `ovsdb:"ip6_src" validate:"max=9223372036854775806"`
	Querier       *bool  `ovsdb:"querier"`
	QueryInterval *int   `ovsdb:"query_interval" validate:"omitempty,max=9223372036854775806"`
	QueryMaxResp  *int   `ovsdb:"query_max_resp" validate:"omitempty,max=9223372036854775806"`
	SeqNo         int    `ovsdb:"seq_no" validate:"max=9223372036854775806"`
	TableSize     *int   `ovsdb:"table_size" validate:"omitempty,max=9223372036854775806"`
}
