// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const LoadBalancerTable = "Load_Balancer"

type (
	LoadBalancerProtocol = string
)

var (
	LoadBalancerProtocolTCP  LoadBalancerProtocol = "tcp"
	LoadBalancerProtocolUDP  LoadBalancerProtocol = "udp"
	LoadBalancerProtocolSCTP LoadBalancerProtocol = "sctp"
)

// LoadBalancer defines an object in Load_Balancer table
type LoadBalancer struct {
	UUID            string                `ovsdb:"_uuid"`
	DatapathGroup   *string               `ovsdb:"datapath_group"`
	Datapaths       []string              `ovsdb:"datapaths"`
	ExternalIDs     map[string]string     `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	LrDatapathGroup *string               `ovsdb:"lr_datapath_group"`
	LsDatapathGroup *string               `ovsdb:"ls_datapath_group"`
	Name            string                `ovsdb:"name" validate:"max=9223372036854775806"`
	Options         map[string]string     `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Protocol        *LoadBalancerProtocol `ovsdb:"protocol" validate:"omitempty,max=9223372036854775806,oneof='tcp' 'udp' 'sctp'"`
	Vips            map[string]string     `ovsdb:"vips" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
}
