// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const LogicalFlowTable = "Logical_Flow"

type (
	LogicalFlowPipeline = string
)

var (
	LogicalFlowPipelineIngress LogicalFlowPipeline = "ingress"
	LogicalFlowPipelineEgress  LogicalFlowPipeline = "egress"
)

// LogicalFlow defines an object in Logical_Flow table
type LogicalFlow struct {
	UUID            string              `ovsdb:"_uuid"`
	Actions         string              `ovsdb:"actions" validate:"max=9223372036854775806"`
	ControllerMeter *string             `ovsdb:"controller_meter" validate:"omitempty,max=9223372036854775806"`
	ExternalIDs     map[string]string   `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	FlowDesc        *string             `ovsdb:"flow_desc" validate:"omitempty,max=9223372036854775806"`
	LogicalDatapath *string             `ovsdb:"logical_datapath"`
	LogicalDpGroup  *string             `ovsdb:"logical_dp_group"`
	Match           string              `ovsdb:"match" validate:"max=9223372036854775806"`
	Pipeline        LogicalFlowPipeline `ovsdb:"pipeline" validate:"max=9223372036854775806,oneof='ingress' 'egress'"`
	Priority        int                 `ovsdb:"priority" validate:"min=0,max=65535"`
	TableID         int                 `ovsdb:"table_id" validate:"min=0,max=32"`
	Tags            map[string]string   `ovsdb:"tags" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
}
