// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const MACBindingTable = "MAC_Binding"

// MACBinding defines an object in MAC_Binding table
type MACBinding struct {
	UUID        string `ovsdb:"_uuid"`
	Datapath    string `ovsdb:"datapath"`
	IP          string `ovsdb:"ip" validate:"max=9223372036854775806"`
	LogicalPort string `ovsdb:"logical_port" validate:"max=9223372036854775806"`
	MAC         string `ovsdb:"mac" validate:"max=9223372036854775806"`
	Timestamp   int    `ovsdb:"timestamp" validate:"max=9223372036854775806"`
}
