// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const MeterTable = "Meter"

type (
	MeterUnit = string
)

var (
	MeterUnitKbps  MeterUnit = "kbps"
	MeterUnitPktps MeterUnit = "pktps"
)

// Meter defines an object in Meter table
type Meter struct {
	UUID  string    `ovsdb:"_uuid"`
	Bands []string  `ovsdb:"bands" validate:"min=1"`
	Name  string    `ovsdb:"name" validate:"max=9223372036854775806"`
	Unit  MeterUnit `ovsdb:"unit" validate:"max=9223372036854775806,oneof='kbps' 'pktps'"`
}
