// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const MulticastGroupTable = "Multicast_Group"

// MulticastGroup defines an object in Multicast_Group table
type MulticastGroup struct {
	UUID      string   `ovsdb:"_uuid"`
	Datapath  string   `ovsdb:"datapath"`
	Name      string   `ovsdb:"name" validate:"max=9223372036854775806"`
	Ports     []string `ovsdb:"ports"`
	TunnelKey int      `ovsdb:"tunnel_key" validate:"min=32768,max=65535"`
}
