// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const PortGroupTable = "Port_Group"

// PortGroup defines an object in Port_Group table
type PortGroup struct {
	UUID  string   `ovsdb:"_uuid"`
	Name  string   `ovsdb:"name" validate:"max=9223372036854775806"`
	Ports []string `ovsdb:"ports" validate:"dive,max=9223372036854775806"`
}
