// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const PortBindingTable = "Port_Binding"

// PortBinding defines an object in Port_Binding table
type PortBinding struct {
	UUID                       string            `ovsdb:"_uuid"`
	AdditionalChassis          []string          `ovsdb:"additional_chassis"`
	AdditionalEncap            []string          `ovsdb:"additional_encap"`
	Chassis                    *string           `ovsdb:"chassis"`
	Datapath                   string            `ovsdb:"datapath"`
	Encap                      *string           `ovsdb:"encap"`
	ExternalIDs                map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	GatewayChassis             []string          `ovsdb:"gateway_chassis"`
	HaChassisGroup             *string           `ovsdb:"ha_chassis_group"`
	LogicalPort                string            `ovsdb:"logical_port" validate:"max=9223372036854775806"`
	MAC                        []string          `ovsdb:"mac" validate:"dive,max=9223372036854775806"`
	MirrorRules                []string          `ovsdb:"mirror_rules"`
	NatAddresses               []string          `ovsdb:"nat_addresses" validate:"dive,max=9223372036854775806"`
	Options                    map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	ParentPort                 *string           `ovsdb:"parent_port" validate:"omitempty,max=9223372036854775806"`
	PortSecurity               []string          `ovsdb:"port_security" validate:"dive,max=9223372036854775806"`
	RequestedAdditionalChassis []string          `ovsdb:"requested_additional_chassis"`
	RequestedChassis           *string           `ovsdb:"requested_chassis"`
	Tag                        *int              `ovsdb:"tag" validate:"omitempty,min=1,max=4095"`
	TunnelKey                  int               `ovsdb:"tunnel_key" validate:"min=1,max=32767"`
	Type                       string            `ovsdb:"type" validate:"max=9223372036854775806"`
	Up                         *bool             `ovsdb:"up"`
	VirtualParent              *string           `ovsdb:"virtual_parent" validate:"omitempty,max=9223372036854775806"`
}
