// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const RBACRoleTable = "RBAC_Role"

// RBACRole defines an object in RBAC_Role table
type RBACRole struct {
	UUID        string            `ovsdb:"_uuid"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Permissions map[string]string `ovsdb:"permissions" validate:"dive,keys,max=9223372036854775806"`
}
