// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const RBACPermissionTable = "RBAC_Permission"

// RBACPermission defines an object in RBAC_Permission table
type RBACPermission struct {
	UUID          string   `ovsdb:"_uuid"`
	Authorization []string `ovsdb:"authorization" validate:"dive,max=9223372036854775806"`
	InsertDelete  bool     `ovsdb:"insert_delete"`
	Table         string   `ovsdb:"table" validate:"max=9223372036854775806"`
	Update        []string `ovsdb:"update" validate:"dive,max=9223372036854775806"`
}
