// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const SBGlobalTable = "SB_Global"

// SBGlobal defines an object in SB_Global table
type SBGlobal struct {
	UUID        string            `ovsdb:"_uuid"`
	Connections []string          `ovsdb:"connections"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Ipsec       bool              `ovsdb:"ipsec"`
	NbCfg       int               `ovsdb:"nb_cfg" validate:"max=9223372036854775806"`
	Options     map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	SSL         *string           `ovsdb:"ssl"`
}
