// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const ServiceMonitorTable = "Service_Monitor"

type (
	ServiceMonitorProtocol = string
	ServiceMonitorStatus   = string
)

var (
	ServiceMonitorProtocolTCP   ServiceMonitorProtocol = "tcp"
	ServiceMonitorProtocolUDP   ServiceMonitorProtocol = "udp"
	ServiceMonitorStatusOnline  ServiceMonitorStatus   = "online"
	ServiceMonitorStatusOffline ServiceMonitorStatus   = "offline"
	ServiceMonitorStatusError   ServiceMonitorStatus   = "error"
)

// ServiceMonitor defines an object in Service_Monitor table
type ServiceMonitor struct {
	UUID        string                  `ovsdb:"_uuid"`
	ChassisName string                  `ovsdb:"chassis_name" validate:"max=9223372036854775806"`
	ExternalIDs map[string]string       `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	IP          string                  `ovsdb:"ip" validate:"max=9223372036854775806"`
	LogicalPort string                  `ovsdb:"logical_port" validate:"max=9223372036854775806"`
	Options     map[string]string       `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Port        int                     `ovsdb:"port" validate:"min=0,max=65535"`
	Protocol    *ServiceMonitorProtocol `ovsdb:"protocol" validate:"omitempty,max=9223372036854775806,oneof='tcp' 'udp'"`
	SrcIP       string                  `ovsdb:"src_ip" validate:"max=9223372036854775806"`
	SrcMAC      string                  `ovsdb:"src_mac" validate:"max=9223372036854775806"`
	Status      *ServiceMonitorStatus   `ovsdb:"status" validate:"omitempty,max=9223372036854775806,oneof='online' 'offline' 'error'"`
}
