// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const SSLTable = "SSL"

// SSL defines an object in SSL table
type SSL struct {
	UUID            string            `ovsdb:"_uuid"`
	BootstrapCaCert bool              `ovsdb:"bootstrap_ca_cert"`
	CaCert          string            `ovsdb:"ca_cert" validate:"max=9223372036854775806"`
	Certificate     string            `ovsdb:"certificate" validate:"max=9223372036854775806"`
	ExternalIDs     map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	PrivateKey      string            `ovsdb:"private_key" validate:"max=9223372036854775806"`
	SSLCiphers      string            `ovsdb:"ssl_ciphers" validate:"max=9223372036854775806"`
	SSLProtocols    string            `ovsdb:"ssl_protocols" validate:"max=9223372036854775806"`
}
