// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

const StaticMACBindingTable = "Static_MAC_Binding"

// StaticMACBinding defines an object in Static_MAC_Binding table
type StaticMACBinding struct {
	UUID               string `ovsdb:"_uuid"`
	Datapath           string `ovsdb:"datapath"`
	IP                 string `ovsdb:"ip" validate:"max=9223372036854775806"`
	LogicalPort        string `ovsdb:"logical_port" validate:"max=9223372036854775806"`
	MAC                string `ovsdb:"mac" validate:"max=9223372036854775806"`
	OverrideDynamicMAC bool   `ovsdb:"override_dynamic_mac"`
}
