// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const BFDTable = "BFD"

type (
	BFDStatus = string
)

var (
	BFDStatusDown      BFDStatus = "down"
	BFDStatusInit      BFDStatus = "init"
	BFDStatusUp        BFDStatus = "up"
	BFDStatusAdminDown BFDStatus = "admin_down"
)

// BFD defines an object in BFD table
type BFD struct {
	UUID        string            `ovsdb:"_uuid"`
	DetectMult  *int              `ovsdb:"detect_mult" validate:"omitempty,min=1,max=9223372036854775806"`
	DstIP       string            `ovsdb:"dst_ip" validate:"max=9223372036854775806"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	LogicalPort string            `ovsdb:"logical_port" validate:"max=9223372036854775806"`
	MinRx       *int              `ovsdb:"min_rx" validate:"omitempty,max=9223372036854775806"`
	MinTx       *int              `ovsdb:"min_tx" validate:"omitempty,min=1,max=9223372036854775806"`
	Options     map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Status      *BFDStatus        `ovsdb:"status" validate:"omitempty,max=9223372036854775806,oneof='down' 'init' 'up' 'admin_down'"`
}
