// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const ChassisTemplateVarTable = "Chassis_Template_Var"

// ChassisTemplateVar defines an object in Chassis_Template_Var table
type ChassisTemplateVar struct {
	UUID        string            `ovsdb:"_uuid"`
	Chassis     string            `ovsdb:"chassis" validate:"max=9223372036854775806"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Variables   map[string]string `ovsdb:"variables" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
}
