// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const ConnectionTable = "Connection"

// Connection defines an object in Connection table
type Connection struct {
	UUID            string            `ovsdb:"_uuid"`
	ExternalIDs     map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	InactivityProbe *int              `ovsdb:"inactivity_probe" validate:"omitempty,max=9223372036854775806"`
	IsConnected     bool              `ovsdb:"is_connected"`
	MaxBackoff      *int              `ovsdb:"max_backoff" validate:"omitempty,min=1000,max=9223372036854775806"`
	OtherConfig     map[string]string `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Status          map[string]string `ovsdb:"status" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Target          string            `ovsdb:"target" validate:"max=9223372036854775806"`
}
