// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const CoppTable = "Copp"

// Copp defines an object in Copp table
type Copp struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Meters      map[string]string `ovsdb:"meters" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
}
