// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const DHCPRelayTable = "DHCP_Relay"

// DHCPRelay defines an object in DHCP_Relay table
type DHCPRelay struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Options     map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Servers     *string           `ovsdb:"servers" validate:"omitempty,max=9223372036854775806"`
}
