// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const ForwardingGroupTable = "Forwarding_Group"

// ForwardingGroup defines an object in Forwarding_Group table
type ForwardingGroup struct {
	UUID        string            `ovsdb:"_uuid"`
	ChildPort   []string          `ovsdb:"child_port" validate:"min=1,dive,max=9223372036854775806"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Liveness    bool              `ovsdb:"liveness"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Vip         string            `ovsdb:"vip" validate:"max=9223372036854775806"`
	Vmac        string            `ovsdb:"vmac" validate:"max=9223372036854775806"`
}
