// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const HAChassisTable = "HA_Chassis"

// HAChassis defines an object in HA_Chassis table
type HAChassis struct {
	UUID        string            `ovsdb:"_uuid"`
	ChassisName string            `ovsdb:"chassis_name" validate:"max=9223372036854775806"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Priority    int               `ovsdb:"priority" validate:"min=0,max=32767"`
}
