// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const LogicalRouterStaticRouteTable = "Logical_Router_Static_Route"

type (
	LogicalRouterStaticRoutePolicy = string
)

var (
	LogicalRouterStaticRoutePolicySrcIP LogicalRouterStaticRoutePolicy = "src-ip"
	LogicalRouterStaticRoutePolicyDstIP LogicalRouterStaticRoutePolicy = "dst-ip"
)

// LogicalRouterStaticRoute defines an object in Logical_Router_Static_Route table
type LogicalRouterStaticRoute struct {
	UUID        string                          `ovsdb:"_uuid"`
	BFD         *string                         `ovsdb:"bfd"`
	ExternalIDs map[string]string               `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	IPPrefix    string                          `ovsdb:"ip_prefix" validate:"max=9223372036854775806"`
	Nexthop     string                          `ovsdb:"nexthop" validate:"max=9223372036854775806"`
	Options     map[string]string               `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	OutputPort  *string                         `ovsdb:"output_port" validate:"omitempty,max=9223372036854775806"`
	Policy      *LogicalRouterStaticRoutePolicy `ovsdb:"policy" validate:"omitempty,max=9223372036854775806,oneof='src-ip' 'dst-ip'"`
	RouteTable  string                          `ovsdb:"route_table" validate:"max=9223372036854775806"`
}
