// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const LogicalRouterPolicyTable = "Logical_Router_Policy"

type (
	LogicalRouterPolicyAction = string
)

var (
	LogicalRouterPolicyActionAllow   LogicalRouterPolicyAction = "allow"
	LogicalRouterPolicyActionDrop    LogicalRouterPolicyAction = "drop"
	LogicalRouterPolicyActionReroute LogicalRouterPolicyAction = "reroute"
)

// LogicalRouterPolicy defines an object in Logical_Router_Policy table
type LogicalRouterPolicy struct {
	UUID        string                    `ovsdb:"_uuid"`
	Action      LogicalRouterPolicyAction `ovsdb:"action" validate:"max=9223372036854775806,oneof='allow' 'drop' 'reroute'"`
	BFDSessions []string                  `ovsdb:"bfd_sessions"`
	ExternalIDs map[string]string         `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Match       string                    `ovsdb:"match" validate:"max=9223372036854775806"`
	Nexthop     *string                   `ovsdb:"nexthop" validate:"omitempty,max=9223372036854775806"`
	Nexthops    []string                  `ovsdb:"nexthops" validate:"dive,max=9223372036854775806"`
	Options     map[string]string         `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Priority    int                       `ovsdb:"priority" validate:"min=0,max=32767"`
}
