// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const LogicalRouterPortTable = "Logical_Router_Port"

// LogicalRouterPort defines an object in Logical_Router_Port table
type LogicalRouterPort struct {
	UUID           string            `ovsdb:"_uuid"`
	DhcpRelay      *string           `ovsdb:"dhcp_relay"`
	Enabled        *bool             `ovsdb:"enabled"`
	ExternalIDs    map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	GatewayChassis []string          `ovsdb:"gateway_chassis"`
	HaChassisGroup *string           `ovsdb:"ha_chassis_group"`
	Ipv6Prefix     []string          `ovsdb:"ipv6_prefix" validate:"dive,max=9223372036854775806"`
	Ipv6RaConfigs  map[string]string `ovsdb:"ipv6_ra_configs" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	MAC            string            `ovsdb:"mac" validate:"max=9223372036854775806"`
	Name           string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Networks       []string          `ovsdb:"networks" validate:"min=1,dive,max=9223372036854775806"`
	Options        map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Peer           *string           `ovsdb:"peer" validate:"omitempty,max=9223372036854775806"`
	Status         map[string]string `ovsdb:"status" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
}
