// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const MeterTable = "Meter"

type (
	MeterUnit = string
)

var (
	MeterUnitKbps  MeterUnit = "kbps"
	MeterUnitPktps MeterUnit = "pktps"
)

// Meter defines an object in Meter table
type Meter struct {
	UUID        string            `ovsdb:"_uuid"`
	Bands       []string          `ovsdb:"bands" validate:"min=1"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Fair        *bool             `ovsdb:"fair"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Unit        MeterUnit         `ovsdb:"unit" validate:"max=9223372036854775806,oneof='kbps' 'pktps'"`
}
