// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const MirrorTable = "Mirror"

type (
	MirrorFilter = string
	MirrorType   = string
)

var (
	MirrorFilterFromLport MirrorFilter = "from-lport"
	MirrorFilterToLport   MirrorFilter = "to-lport"
	MirrorFilterBoth      MirrorFilter = "both"
	MirrorTypeGre         MirrorType   = "gre"
	MirrorTypeErspan      MirrorType   = "erspan"
	MirrorTypeLocal       MirrorType   = "local"
)

// Mirror defines an object in Mirror table
type Mirror struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Filter      MirrorFilter      `ovsdb:"filter" validate:"max=9223372036854775806,oneof='from-lport' 'to-lport' 'both'"`
	Index       int               `ovsdb:"index" validate:"max=9223372036854775806"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Sink        string            `ovsdb:"sink" validate:"max=9223372036854775806"`
	Type        MirrorType        `ovsdb:"type" validate:"max=9223372036854775806,oneof='gre' 'erspan' 'local'"`
}
