// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const NATTable = "NAT"

type (
	NATType = string
)

var (
	NATTypeDNAT        NATType = "dnat"
	NATTypeSNAT        NATType = "snat"
	NATTypeDNATAndSNAT NATType = "dnat_and_snat"
)

// NAT defines an object in NAT table
type NAT struct {
	UUID              string            `ovsdb:"_uuid"`
	AllowedExtIPs     *string           `ovsdb:"allowed_ext_ips"`
	ExemptedExtIPs    *string           `ovsdb:"exempted_ext_ips"`
	ExternalIDs       map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	ExternalIP        string            `ovsdb:"external_ip" validate:"max=9223372036854775806"`
	ExternalMAC       *string           `ovsdb:"external_mac" validate:"omitempty,max=9223372036854775806"`
	ExternalPortRange string            `ovsdb:"external_port_range" validate:"max=9223372036854775806"`
	GatewayPort       *string           `ovsdb:"gateway_port"`
	LogicalIP         string            `ovsdb:"logical_ip" validate:"max=9223372036854775806"`
	LogicalPort       *string           `ovsdb:"logical_port" validate:"omitempty,max=9223372036854775806"`
	Match             string            `ovsdb:"match" validate:"max=9223372036854775806"`
	Options           map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Priority          int               `ovsdb:"priority" validate:"min=0,max=32767"`
	Type              NATType           `ovsdb:"type" validate:"max=9223372036854775806,oneof='dnat' 'snat' 'dnat_and_snat'"`
}
