// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const NBGlobalTable = "NB_Global"

// NBGlobal defines an object in NB_Global table
type NBGlobal struct {
	UUID           string            `ovsdb:"_uuid"`
	Connections    []string          `ovsdb:"connections"`
	ExternalIDs    map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	HvCfg          int               `ovsdb:"hv_cfg" validate:"max=9223372036854775806"`
	HvCfgTimestamp int               `ovsdb:"hv_cfg_timestamp" validate:"max=9223372036854775806"`
	Ipsec          bool              `ovsdb:"ipsec"`
	Name           string            `ovsdb:"name" validate:"max=9223372036854775806"`
	NbCfg          int               `ovsdb:"nb_cfg" validate:"max=9223372036854775806"`
	NbCfgTimestamp int               `ovsdb:"nb_cfg_timestamp" validate:"max=9223372036854775806"`
	Options        map[string]string `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	SbCfg          int               `ovsdb:"sb_cfg" validate:"max=9223372036854775806"`
	SbCfgTimestamp int               `ovsdb:"sb_cfg_timestamp" validate:"max=9223372036854775806"`
	SSL            *string           `ovsdb:"ssl"`
}
