// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const PortGroupTable = "Port_Group"

// PortGroup defines an object in Port_Group table
type PortGroup struct {
	UUID        string            `ovsdb:"_uuid"`
	ACLs        []string          `ovsdb:"acls"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Ports       []string          `ovsdb:"ports"`
}
