// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const QoSTable = "QoS"

type (
	QoSAction    = string
	QoSBandwidth = string
	QoSDirection = string
)

var (
	QoSActionDSCP         QoSAction    = "dscp"
	QoSActionMark         QoSAction    = "mark"
	QoSBandwidthRate      QoSBandwidth = "rate"
	QoSBandwidthBurst     QoSBandwidth = "burst"
	QoSDirectionFromLport QoSDirection = "from-lport"
	QoSDirectionToLport   QoSDirection = "to-lport"
)

// QoS defines an object in QoS table
type QoS struct {
	UUID        string            `ovsdb:"_uuid"`
	Action      map[string]int    `ovsdb:"action" validate:"dive,keys,max=9223372036854775806,oneof='dscp' 'mark',endkeys,min=0,max=4294967295"`
	Bandwidth   map[string]int    `ovsdb:"bandwidth" validate:"dive,keys,max=9223372036854775806,oneof='rate' 'burst',endkeys,min=1,max=4294967295"`
	Direction   QoSDirection      `ovsdb:"direction" validate:"max=9223372036854775806,oneof='from-lport' 'to-lport'"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Match       string            `ovsdb:"match" validate:"max=9223372036854775806"`
	Priority    int               `ovsdb:"priority" validate:"min=0,max=32767"`
}
