// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const SamplingAppTable = "Sampling_App"

type (
	SamplingAppType = string
)

var (
	SamplingAppTypeDrop   SamplingAppType = "drop"
	SamplingAppTypeACLNew SamplingAppType = "acl-new"
	SamplingAppTypeACLEst SamplingAppType = "acl-est"
)

// SamplingApp defines an object in Sampling_App table
type SamplingApp struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	ID          int               `ovsdb:"id" validate:"min=1,max=255"`
	Type        SamplingAppType   `ovsdb:"type" validate:"max=9223372036854775806,oneof='drop' 'acl-new' 'acl-est'"`
}
