// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const SampleCollectorTable = "Sample_Collector"

// SampleCollector defines an object in Sample_Collector table
type SampleCollector struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	ID          int               `ovsdb:"id" validate:"min=1,max=255"`
	Name        string            `ovsdb:"name" validate:"max=9223372036854775806"`
	Probability int               `ovsdb:"probability" validate:"min=0,max=65535"`
	SetID       int               `ovsdb:"set_id" validate:"min=1,max=4294967295"`
}
